all: globals.h valueIteration.h dealer.h player.h valueIteration.cpp dealer.cpp player.cpp main.cpp
	g++ -std=c++11 -o main.out valueIteration.cpp dealer.cpp player.cpp main.cpp
clean:
	rm -f main.out
